title: Michal Oláh
author: Michal Oláh
subtitle: ""
description: "If something is not fun, it's not worth doing."
tagline: "having fun developing web applications"

github: m1k3
twitter: michalolah
linkedin: http://www.linkedin.com/pub/oláh-michal/76/a22/7aa
slideshare: http://www.slideshare.net/olahmichal

destination: ./public
exclude: [public, Gemfile, Gemfile.lock, Rakefile, README.md]

permalink: /blog/:categories/:title
#markdown: rdiscount
markdown: redcarpet
pygments: true
