title: Circulus
author: Michal Oláh
subtitle: ""
description: ""

github: m1k3
twitter: michalolah
linkedin: http://www.linkedin.com/pub/oláh-michal/76/a22/7aa

source: ./_source
destination: public
exclude: [public, Gemfile, Gemfile.lock, Rakefile, README.md]

permalink: /blog/:categories/:title
#markdown: rdiscount
markdown: redcarpet
pygments: true
