domain: michalolah.com
url: https://michalolah.com
title: Michal Oláh
author: Michal Oláh
description: Crafting application for over 20 years.
tagline: crafting applications

github_handle: m1k3
twitter: michalolah
linkedin: michalolah
slideshare: olahmichal
sitepoint: molah

exclude: [public, Gemfile, Gemfile.lock, Rakefile, README.md]

permalink: /blog/:categories/:title

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
