url: "http://michalolah.com"
title: "Michal Oláh"
author: "Michal Oláh"
subtitle: ""
description: "If something is not fun, it's not worth doing."
tagline: "having fun developing web applications"

github_handle: m1k3
twitter: michalolah
linkedin: michalolah
slideshare: olahmichal
sitepoint: molah

destination: ./public
exclude: [public, Gemfile, Gemfile.lock, Rakefile, README.md]

permalink: /blog/:categories/:title
#markdown: rdiscount
markdown: redcarpet
pygments: true
